apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      namespace: instapro-latest
      name: db
    spec:
      ports:
        - name: db
          port: 27017
          targetPort: 27017
      selector:
        app: db

  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      namespace: instapro-latest
      labels:
        app: db
      name: db
    spec:
      replicas: 1
      strategy: {}
      template:
        metadata:
          labels:
            app: db
        spec:
          strategy:
            type: Recreate
          containers:
            - image: mongo:latest
              name: db
              imagePullPolicy: Always
              resources: {}
              stdin: true
              tty: true
          restartPolicy: Always
          imagePullSecrets:
            - name: regcred
kind: List
metadata: {}
