apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      namespace: instapro-latest
      name: web
      labels:
        app: web
    spec:
      ports:
        - port: 80
          targetPort: 80
      selector:
        app: web
      type: NodePort

  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      labels:
        app: web
      name: web
      namespace: instapro-latest
    spec:
      replicas: 1
      strategy: {}
      template:
        metadata:
          labels:
            app: web
        spec:
          strategy:
            type: Recreate
          containers:
            - image: registry.anexsolutions.co.uk/instapro/web:latest
              name: web
              imagePullPolicy: Always
              resources: {}
              stdin: true
              tty: true
          restartPolicy: Always
          imagePullSecrets:
            - name: regcred
kind: List
metadata: {}
